version: '3.8'

services:
  owner-db:
    image: mysql:latest
    container_name: owner-db
    restart: always
    networks:
      - owner-db-net
    volumes:
#      - owner-volume:/data/db
      - owner-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3310:3306"
  #    command:
  #      --init-connect=‘GRANT CREATE USER ON *.* TO’root’@‘%’;FLUSH PRIVILEGES;’

  backend:
    image: owner-image
    container_name: owner-back
    depends_on:
      - owner-db
    restart: always
    networks:
      - owner-db-net
    ports:
      - "8082:8082"

networks:
  owner-db-net:
    external: true

volumes:
  owner-volume:
    external: true